# Taken and modified from acemod/ace3
name: Release Drafter

on:
  push:
    branches:
    - master

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        if: github.repository == 'mjc4wilton/jsoc_ew'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
